const books= [
    {id:"b1", title:"The Silence of the Lambs", stars:"⭐⭐⭐⭐", author:"Thomas Harris", price:16.99,img:'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0995/9780099586579.jpg',synopsis:'A psychopath known as "Buffalo Bill" (Ted Levine) is kidnapping and murdering young women across the Midwest. Believing it takes one to know one, the F.B.I. sends trainee Clarice Starling (Jodie Foster) to interview a demented prisoner who may provide psychological insight and clues to the killers actions.', pages:338, genre:'thriller'},
    {id:"b2", title:"The Shinning", stars:"⭐⭐⭐⭐⭐", author:"Stephen King", price:12.99,img:'https://i.pinimg.com/originals/55/23/e6/5523e6b39d0a1d1118877eaf23a8c23b.jpg',synopsis:'The Shining centers on the life of Jack Torrance, a struggling writer and recovering alcoholic who accepts a position as the off-season caretaker of the historic Overlook Hotel in the Colorado Rockies. His family accompanies him on this job, including his young son Danny Torrance, who possesses "the shining", an array of psychic abilities that allow Danny to see the hotels past.', pages:447, genre:'horror'},
    {id:"b3", title:"The Notebook", stars:"⭐⭐⭐⭐", author:"Nicholas Sparks", price:13.49,img:'https://upload.wikimedia.org/wikipedia/en/d/d9/The_Notebook_Cover.jpg',synopsis:'The Notebook is an achingly tender story about the enduring power of love, a story of miracles that will stay with you forever. Set amid the austere beauty of coastal North Carolina in 1946, The Notebook begins with the story of Noah Calhoun, a rural Southerner returned home from World War II.', pages:214, genre:'romance'},
    {id:"b4", title:"The Trial", stars:"⭐⭐⭐⭐", author:"Franz Kafka", price:11.49,img:'https://images-na.ssl-images-amazon.com/images/I/51zkg7Yy-VL._SX331_BO1,204,203,200_.jpg',synopsis:'An ambitious, worldly young bank official named Joseph K. is arrested by two warders "one fine morning," although he has done nothing wrong. K. is indignant and outraged. The morning happens to be that of his thirtieth birthday. One year later, on the morning of his thirty-first birthday, two warders again come for K. They take him to a quarry outside of town and kill him.', pages:304, genre:'classics'},
    {id:"b5", title:"Moby Dick", stars:"⭐⭐⭐⭐", author:"Herman Melville", price:13.49,img:'https://i.pinimg.com/originals/0c/72/e3/0c72e3baac4b6807c025c45b47c2c0b4.jpg',synopsis:'The book is the sailor Ishmaels narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on Moby Dick, the giant white sperm whale that on the ships previous voyage bit off Ahabs leg at the knee.', pages:765, genre:'classics'},
    {id:"b6", title:"Fight Club", stars:"⭐⭐⭐⭐", author:"Chuk Palahniuk", price:13.49,img:'https://prodimage.images-bn.com/pimages/9780393355949_p0_v6_s550x406.jpg',synopsis:'Fight Club’s estranged narrator leaves his lackluster job when he comes under the thrall of Tyler Durden, an enigmatic young man who holds secret after-hours boxing matches in the basement of bars. There, two men fight "as long as they have to." This is a gloriously original work that exposes the darkness at the core of our modern world.', pages:335, genre:'thriller'},
    {id:"b7", title:"Solaris", stars:"⭐⭐⭐⭐", author:"Stanislaw Lem", price:13.49,img:'https://www.newrafael.com/wp-content/uploads/2014/06/solaris-stanislaw-lem.jpg',synopsis:'The story takes place in a distant future where humans engage in interplanetary travel. Kris Kelvan is a psychologist who travels to a space station orbiting the planet Solaris to study an enormous and potentially sentient ocean on the surface. Scientists have studied the ocean for decades fruitlessly. They beam X-rays to the ocean in an unauthorized experiment that affects them psychologically.', pages:204, genre:'sf'},
    {id:"b8", title:"The Idiot", stars:"⭐⭐⭐⭐", author:"Fyodor Dostoevsky", price:13.49,img:'https://m.media-amazon.com/images/I/41vcir8ILAL.jpg',synopsis:'A saintly man, Prince Myshkin, is thrust into the heart of a society more concerned with wealth, power, and sexual conquest than with the ideals of Christianity. Myshkin soon finds himself at the center of a violent love triangle in which a notorious woman and a beautiful young girl become rivals for his affections.Extortion, scandal, and murder follow, testing Myshkin’s moral feelings.', pages:573, genre:'classics'},
    {id:"b9", title:"Great Expectations", stars:"⭐⭐⭐⭐", author:"Charles Dickens", price:15.49,img:'https://m.media-amazon.com/images/I/51pqUWvj6NL.jpg',synopsis:'', pages:367, genre:'classics'},
    {id:"b10", title:"The Mysterious Affair at Styles", stars:"⭐⭐⭐⭐", author:"Agatha Christie", price:13.49,img:'https://cdn.waterstones.com/bookjackets/large/9780/0075/9780007527496.jpg',synopsis:'After the Great War, life can never be the same again. Wounds need healing, and the horror of violent death banished into memory.Captain Arthur Hastings is invited to the rolling country estate of Styles to recuperate from injuries sustained at the Front. It is the last place he expects to encounter murder. Fortunately he knows a former detective, a Belgian refugee, who has grown bored of retirement ', pages:288, genre:'detective'},
    


]

export const newReleases= [
    {id:'n1', title:'Harry Potter',author:'J.K.Rowling', price:17.99, img:'https://images-na.ssl-images-amazon.com/images/I/71ykU-RQ0nL._AC_SY741_.jpg' },
    {id:'n2', title:'The Da Vinci Code', author:'Dan Brown', price:14.99, img:'https://images-na.ssl-images-amazon.com/images/I/51nTKunde0L._SX319_BO1,204,203,200_.jpg' },
    {id:'n3', title:'The Clocks', author:'Agatha Christie', price:17.99, img:'https://i.pinimg.com/236x/8c/6e/6e/8c6e6e08afa038f46f537679862b4ff7--agatha-christie-book-covers.jpg' },
    {id:'n4', title:'Crime and Punishment', author:'Fyodor Dostoevsky', price:17.99, img:'https://i.pinimg.com/originals/68/c5/4c/68c54c9599ba37d9ab98c0c51afe2298.png' },
   
   
]

export default books